"""Configuration constants for eruption-forecast package."""

from eruption_forecast.config.constants import (
    PLOT_DPI,
    TRAIN_TEST_SPLIT,
    DEFAULT_CV_SPLITS,
    THRESHOLD_RESOLUTION,
    PLOT_SEPARATOR_LENGTH,
    DEFAULT_SAMPLING_STRATEGY,
    DEFAULT_N_SIGNIFICANT_FEATURES,
    ERUPTION_PROBABILITY_THRESHOLD,
)


__all__ = [
    "TRAIN_TEST_SPLIT",
    "DEFAULT_CV_SPLITS",
    "DEFAULT_N_SIGNIFICANT_FEATURES",
    "DEFAULT_SAMPLING_STRATEGY",
    "ERUPTION_PROBABILITY_THRESHOLD",
    "THRESHOLD_RESOLUTION",
    "PLOT_DPI",
    "PLOT_SEPARATOR_LENGTH",
]
